on:
  push:
    paths: ['vignettes/**.Rmd']
  workflow_dispatch:

name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true
          cache-version: 1
          extra-packages: |
            any::remotes
            local::.

      - name: Render README
        run: |
          Rscript -e 'rmarkdown::render(input = "inst/scripts/README.Rmd", output_dir = ".")'

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git commit -m 'Re-build README.md file'
          git push origin
